export const PATHS = {
  HOME: '/',
  HISTORY: '/history',
  MYGDATA: '/my-g-data',
  OURGDATA: '/our-g-data',
  ACCOUNT: '/account',
  PERSONAL: '/my-g-data/personal-data',
  CONSENT: '/my-g-data/consent',
  COMPANY: '/my-g-data/company',
  REWARDS: '/my-g-data/rewards',
  SCREEN: '/my-g-data/screen-data',
  SIGNUP: '/signup',
  LOGIN: '/login',
  RESETPASSWORD: '/reset_password',
  PRIVACY: 'https://www.g-datalabs.com/privacy_policy',
  COOKIEPOLICY: 'https://www.g-datalabs.com/cookie_and_policy',
  TERMS: 'https://www.g-datalabs.com/terms_condition',
  CONFIRMPASSWORD: '/reset_password/confirm',
  DATA: '/our-g-data/data',
  ASSETS: '/our-g-data/assets',
  BUY: '/our-g-data/data/buy',
};
