export enum DATATIMETYPE {
  DAY = '1 DAY',
  HOUR15 = '15 HOURS',
  HOUR1 = '1 HOUR',
  HOUR4 = '4 HOURS',
  YEAR1 = '1 YEAR',
}
export const DATATIMETYPESOPTIONS = [
  { label: DATATIMETYPE.DAY, value: DATATIMETYPE.DAY },
  { label: DATATIMETYPE.HOUR15, value: DATATIMETYPE.HOUR15 },
  { label: DATATIMETYPE.HOUR1, value: DATATIMETYPE.HOUR1 },
  { label: DATATIMETYPE.HOUR4, value: DATATIMETYPE.HOUR4 },
  { label: DATATIMETYPE.YEAR1, value: DATATIMETYPE.YEAR1 },
];
